global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'host-node'
    static_configs:
      - targets: ['node-exporter-host:9100']          

  - job_name: 'nginx-central'
    static_configs:
      - targets: ['nginx-exporter-central:9113']         

  - job_name: 'nginx-facultyA'
    static_configs:
      - targets: ['nginx-exporter-facultyA:9113']  

  - job_name: 'nginx-facultyB'
    static_configs:
      - targets: ['nginx-exporter-facultyB:9113']      

  - job_name: 'nginx-facultyC'
    static_configs:
      - targets: ['nginx-exporter-facultyC:9113']  

  - job_name: 'nginx-facultyD'
    static_configs:
      - targets: ['nginx-exporter-facultyD:9113'] 

  - job_name: 'nginx-facultyE'
    static_configs:
      - targets: ['nginx-exporter-facultyE:9113'] 

  - job_name: 'central-custom'
    static_configs:
      - targets: ['central-nginx:3000']                   

  - job_name: 'facultyA-custom'
    static_configs:
      - targets: ['facultyA-edge:3001']  

  - job_name: 'facultyB-custom'
    static_configs:
      - targets: ['facultyB-edge:3002']   

  - job_name: 'facultyC-custom'
    static_configs:
      - targets: ['facultyC-edge:3003']   

  - job_name: 'facultyD-custom'
    static_configs:
      - targets: ['facultyD-edge:3004']  

  - job_name: 'facultyE-custom'
    static_configs:
      - targets: ['facultyE-edge:3005']                    

  - job_name: 'logporter'
    scrape_interval: 5s                                 
    static_configs:
      - targets: ['logporter:9333']                      